---
output: slidy_presentation
---

# Challenge 1


Using pipes, subset the data to include individuals collected before 1995,
and retain the columns `year`, `sex`, and `weight.`


---

# Challenge 2


Create a new dataframe from the survey data that meets the following
criteria:

- contains only the `species_id` column and a column that contains
values that are the square-root of `hindfoot_length` values (e.g. a new column
`hindfoot_sqrt`).
- In this `hindfoot_sqrt` column, all values are < 3.

Hint: think about how the commands should be ordered


---

# Challenge 3


How many times was each `plot_type` surveyed?


---

# Challenge 4


Use `group_by()` and `summarize()` to find the mean, min, and max hindfoot
length for each species.


---

# Challenge 5


What was the heaviest animal measured in each year? Return the columns `year`,
`genus`, `species`, and `weight`.

Hint: Use `filter()` rather than `summarize()`.


---

# Challenge 6


Make a scatterplot of `hindfoot_length` vs `weight`, but only for the
`species_id` `"DM"`.

- Use the dataset we'd created, `just_dm`
- Use our ggplot2 code above but with this new dataset in place of `surveys`.


---

# Challenge 7


Make a scatterplot of mean `hindfoot_length` vs mean `weight`, where
each point is a species, and where the sizes of points indicate the
sample size.

- Use the dataset we'd created, `stat_summary`

- Use our ggplot code with the aesthetics
  `x=mean_wt` and `y=mean_hfl`, plus `size=n`.


---

# Challenge 8


- Use the `year_summary` dataset to make a line plot of counts of each
  species by year, with a different line for each species.

- Use `aes(linetype=sex)` to have different line types for the two
  sexes.


---

# Challenge 9


A variant on the box plot is the violin plot. Use `geom_violin()` to
make violin plots of `hindfoot_length` by `species_id`.


---

# Challenge 10


Try using `geom_histogram()` to make a histogram visualization of the
distribution of `weight`.

Hint: You want `weight` as the x-axis aesthetic. Try specifying `bins`
in `geom_histogram()`.


---

# Challenge 11


Use the `year_summary` dataset and make scatterplots of mean hindfoot
length vs mean weight (with each point being a species), faceting by year.

- Use aesthetics `x=mean_wt` and `y=mean_hfl`

- Use `geom_point(aes(color=species_id, shape=sex))`

- Use `facet_wrap(~ year)`


---

# Challenge 12


- Create a new R Markdown document.
- Delete all of the R code chunks and write a bit of Markdown (some sections, some italicized
text, and an itemized list).
- Convert the document to a webpage.


---

# Challenge 13


Add code chunks to

- Load the ggplot2 package
- Read the portal data
- Create a plot


---

# Challenge 14


Use chunk options to control the size of a figure and to hide the
code.


---

# Challenge 15


Try out a bit of in-line R code.



# Capstone project

Create and compile an R Markdown report:

1. Load the `portal_clean.csv` data.

2. Create boxplots of weight by sex.

3. Create a histogram of hindfoot lengths.

4. Create a scatterplot of hindfoot length vs weight for the species
`"DM"`, `"DO"`, and `"DS"`. _Use different colors for the three
species, and put the three species in different panels._

5. Create a line plot of the counts of `"DM"` in `"Rodent Exclosure"` plots over time.

6. Create a table of counts of `"DM"` by plot type for the year 1977.
